common_process:
  #---------------Process 1---------------#
  - is_first_name:
    is_tail:
    is_translation_tail:
    word:
    translation:
  #---------------Process 2---------------#
  - is_first_name:
    is_tail:
    is_translation_tail:
    word:
    translation:

character_name_list:
  #----------------Character 1----------------#
  - first_name:
    first_name_translation:
    last_name:
    last_name_translation:
    process:
      #---------------Process 1---------------#
      - is_first_name:
        is_tail:
        is_translation_tail:
        word:
        translation:
      #---------------Process 2---------------#
      - is_first_name:
        is_tail:
        is_translation_tail:
        word:
        translation:
  #----------------Character 2----------------#
  - first_name:
    first_name_translation:
    last_name:
    last_name_translation:
    process:
      - is_first_name:
        is_tail:
        is_translation_tail:
        word:
        translation:
