text_analyzer:
  newline_character: "\\n"
  unnecessary_newline_character: ["、\\n"]
  regular_expression: [
      "[\\\\n…「」]+", #
      "\\{\"Address.*\\}",
    ]
  separator: ["\\B", "\\A"]
  separator_need_translate: [["「", "“"], ["」", "”"]]
