text_analyzer:
  newline_character: "\\n"
  newline_character_trigger: [".*[。…！？]+"]
  regular_expression: [
      "[\\\\n…]+", # \\\\->\
      "\\{\"Address.*\\}",
    ]
  separator: ["\\B", "\\A"]
  separator_need_translate: [["「", "“"], ["」", "”"]]
