# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_machine_trans.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MachineTrans(object):
    def setupUi(self, MachineTrans):
        MachineTrans.setObjectName("MachineTrans")
        MachineTrans.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MachineTrans.sizePolicy().hasHeightForWidth())
        MachineTrans.setSizePolicy(sizePolicy)
        self.machineTransWidget = QtWidgets.QWidget(MachineTrans)
        self.machineTransWidget.setGeometry(QtCore.QRect(0, 100, 960, 620))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machineTransWidget.sizePolicy().hasHeightForWidth())
        self.machineTransWidget.setSizePolicy(sizePolicy)
        self.machineTransWidget.setObjectName("machineTransWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.machineTransWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.machineTransWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.machineTransBrowser = QtWidgets.QTextBrowser(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machineTransBrowser.sizePolicy().hasHeightForWidth())
        self.machineTransBrowser.setSizePolicy(sizePolicy)
        self.machineTransBrowser.setMinimumSize(QtCore.QSize(920, 520))
        self.machineTransBrowser.setMaximumSize(QtCore.QSize(920, 520))
        self.machineTransBrowser.setObjectName("machineTransBrowser")
        self.horizontalLayout.addWidget(self.machineTransBrowser)
        self.verticalLayout.addWidget(self.widget)
        self.startTransWidget = QtWidgets.QWidget(self.machineTransWidget)
        self.startTransWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.startTransWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.startTransWidget.setObjectName("startTransWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.startTransWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.startTransButton = QtWidgets.QPushButton(self.startTransWidget)
        self.startTransButton.setMinimumSize(QtCore.QSize(80, 25))
        self.startTransButton.setMaximumSize(QtCore.QSize(80, 25))
        self.startTransButton.setObjectName("startTransButton")
        self.horizontalLayout_3.addWidget(self.startTransButton)
        self.verticalLayout.addWidget(self.startTransWidget)

        self.retranslateUi(MachineTrans)
        QtCore.QMetaObject.connectSlotsByName(MachineTrans)

    def retranslateUi(self, MachineTrans):
        _translate = QtCore.QCoreApplication.translate
        MachineTrans.setWindowTitle(_translate("MachineTrans", "Form"))
        self.startTransButton.setText(_translate("MachineTrans", "开始翻译"))
