# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        self.menuWidget = QtWidgets.QWidget(Menu)
        self.menuWidget.setGeometry(QtCore.QRect(10, 0, 960, 40))
        self.menuWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.menuWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.menuWidget.setObjectName("menuWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menuWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.machineTranslateButton = QtWidgets.QPushButton(self.menuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machineTranslateButton.sizePolicy().hasHeightForWidth())
        self.machineTranslateButton.setSizePolicy(sizePolicy)
        self.machineTranslateButton.setMinimumSize(QtCore.QSize(80, 25))
        self.machineTranslateButton.setMaximumSize(QtCore.QSize(80, 25))
        self.machineTranslateButton.setObjectName("machineTranslateButton")
        self.horizontalLayout.addWidget(self.machineTranslateButton)
        self.wordCountButton = QtWidgets.QPushButton(self.menuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCountButton.sizePolicy().hasHeightForWidth())
        self.wordCountButton.setSizePolicy(sizePolicy)
        self.wordCountButton.setMinimumSize(QtCore.QSize(80, 25))
        self.wordCountButton.setMaximumSize(QtCore.QSize(80, 25))
        self.wordCountButton.setObjectName("wordCountButton")
        self.horizontalLayout.addWidget(self.wordCountButton)
        self.settingButton = QtWidgets.QPushButton(self.menuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setMinimumSize(QtCore.QSize(80, 25))
        self.settingButton.setMaximumSize(QtCore.QSize(80, 25))
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout.addWidget(self.settingButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.machineTranslateButton.setText(_translate("Menu", "机器翻译"))
        self.wordCountButton.setText(_translate("Menu", "词频统计"))
        self.settingButton.setText(_translate("Menu", "设置"))
