# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_word_count.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WordCount(object):
    def setupUi(self, WordCount):
        WordCount.setObjectName("WordCount")
        WordCount.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WordCount.sizePolicy().hasHeightForWidth())
        WordCount.setSizePolicy(sizePolicy)
        self.wordCountWidget = QtWidgets.QWidget(WordCount)
        self.wordCountWidget.setGeometry(QtCore.QRect(0, 100, 960, 620))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCountWidget.sizePolicy().hasHeightForWidth())
        self.wordCountWidget.setSizePolicy(sizePolicy)
        self.wordCountWidget.setObjectName("wordCountWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wordCountWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.browserWidget = QtWidgets.QWidget(self.wordCountWidget)
        self.browserWidget.setObjectName("browserWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.browserWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wordCountBrowser = QtWidgets.QTextBrowser(self.browserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCountBrowser.sizePolicy().hasHeightForWidth())
        self.wordCountBrowser.setSizePolicy(sizePolicy)
        self.wordCountBrowser.setMinimumSize(QtCore.QSize(900, 520))
        self.wordCountBrowser.setMaximumSize(QtCore.QSize(920, 520))
        self.wordCountBrowser.setObjectName("wordCountBrowser")
        self.horizontalLayout.addWidget(self.wordCountBrowser)
        self.verticalLayout.addWidget(self.browserWidget)
        self.startCountWidget = QtWidgets.QWidget(self.wordCountWidget)
        self.startCountWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.startCountWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.startCountWidget.setObjectName("startCountWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.startCountWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.startCountButton = QtWidgets.QPushButton(self.startCountWidget)
        self.startCountButton.setMinimumSize(QtCore.QSize(80, 25))
        self.startCountButton.setMaximumSize(QtCore.QSize(80, 25))
        self.startCountButton.setObjectName("startCountButton")
        self.horizontalLayout_3.addWidget(self.startCountButton)
        self.verticalLayout.addWidget(self.startCountWidget)

        self.retranslateUi(WordCount)
        QtCore.QMetaObject.connectSlotsByName(WordCount)

    def retranslateUi(self, WordCount):
        _translate = QtCore.QCoreApplication.translate
        WordCount.setWindowTitle(_translate("WordCount", "Form"))
        self.startCountButton.setText(_translate("WordCount", "开始统计"))
